"""initial schema

Revision ID: 789f0d0a246b
Revises:
Create Date: 2026-09-04 08:42:21.730505

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '789f0d0a246b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stored_files',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('original_name', sa.String(length=255), nullable=False),
        sa.Column('stored_name', sa.String(length=255), nullable=False),
        sa.Column('mime_type', sa.String(length=255), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('processing_status', sa.String(length=50), nullable=False),
        sa.Column('scan_status', sa.String(length=50), nullable=True),
        sa.Column('scan_details', sa.String(length=500), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('requires_attention', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stored_name'),
        schema='files',
    )
    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.String(length=36), nullable=False),
        sa.Column('level', sa.String(length=50), nullable=False),
        sa.Column('message', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['files.stored_files.id']),
        sa.PrimaryKeyConstraint('id'),
        schema='files',
    )
    op.create_index(op.f('ix_files_alerts_created_at'), 'alerts', ['created_at'], unique=False, schema='files')
    op.create_index(op.f('ix_files_alerts_file_id'), 'alerts', ['file_id'], unique=False, schema='files')
    op.create_index(
        op.f('ix_files_stored_files_created_at'), 'stored_files', ['created_at'], unique=False, schema='files'
    )
    op.create_index(
        'ix_files_stored_files_original_name_trgm',
        'stored_files',
        ['original_name'],
        unique=False,
        schema='files',
        postgresql_using='gin',
        postgresql_ops={'original_name': 'gin_trgm_ops'},
    )
    op.create_index(
        'ix_files_stored_files_title_trgm',
        'stored_files',
        ['title'],
        unique=False,
        schema='files',
        postgresql_using='gin',
        postgresql_ops={'title': 'gin_trgm_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_files_stored_files_title_trgm',
        table_name='stored_files',
        schema='files',
        postgresql_using='gin',
        postgresql_ops={'title': 'gin_trgm_ops'},
    )
    op.drop_index(
        'ix_files_stored_files_original_name_trgm',
        table_name='stored_files',
        schema='files',
        postgresql_using='gin',
        postgresql_ops={'original_name': 'gin_trgm_ops'},
    )
    op.drop_index(op.f('ix_files_stored_files_created_at'), table_name='stored_files', schema='files')
    op.drop_index(op.f('ix_files_alerts_file_id'), table_name='alerts', schema='files')
    op.drop_index(op.f('ix_files_alerts_created_at'), table_name='alerts', schema='files')
    op.drop_table('alerts', schema='files')
    op.drop_table('stored_files', schema='files')
    # ### end Alembic commands ###
