from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f817c24769df'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Создать шесть таблиц платёжного шлюза."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('balance', sa.Numeric(precision=27, scale=3), nullable=False),
        sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            "currency IN ('RUB', 'USD', 'EUR', 'KZT', 'JPY', 'KWD')",
            name=op.f('ck_accounts_currency_enum_values'),
        ),
        sa.CheckConstraint('balance >= 0', name=op.f('ck_accounts_balance_non_negative')),
        sa.CheckConstraint('version >= 1', name=op.f('ck_accounts_version_positive')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    )
    op.create_table(
        'idempotency_keys',
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('request_hash', sa.String(length=64), nullable=False),
        sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('expires_at > created_at', name=op.f('ck_idempotency_keys_expires_after_created')),
        sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys')),
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table(
        'outbox',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('aggregate_type', sa.String(length=64), nullable=False),
        sa.Column('aggregate_id', sa.Uuid(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    )
    op.create_index(
        'ix_outbox_unpublished',
        'outbox',
        ['created_at'],
        unique=False,
        postgresql_where=sa.text('published_at IS NULL'),
    )
    op.create_table(
        'processed_events',
        sa.Column('consumer', sa.String(length=128), nullable=False),
        sa.Column('event_id', sa.String(length=255), nullable=False),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('consumer', 'event_id', name=op.f('pk_processed_events')),
    )
    op.create_index(op.f('ix_processed_events_processed_at'), 'processed_events', ['processed_at'], unique=False)
    op.create_table(
        'provider_webhook_events',
        sa.Column('provider_event_id', sa.String(length=255), nullable=False),
        sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
        sa.Column('provider_status', sa.String(length=10), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            "provider_payment_id != ''",
            name=op.f('ck_provider_webhook_events_provider_payment_id_not_empty'),
        ),
        sa.CheckConstraint(
            "provider_status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'REFUNDED')",
            name=op.f('ck_provider_webhook_events_provider_status_enum_values'),
        ),
        sa.PrimaryKeyConstraint('provider_event_id', name=op.f('pk_provider_webhook_events')),
    )
    op.create_index(
        op.f('ix_provider_webhook_events_received_at'),
        'provider_webhook_events',
        ['received_at'],
        unique=False,
    )
    op.create_table(
        'payments',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('from_account_id', sa.Uuid(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=27, scale=3), nullable=False),
        sa.Column('status', sa.String(length=10), nullable=False),
        sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
        sa.Column('provider_status', sa.String(length=10), nullable=True),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            "provider_status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'REFUNDED')",
            name=op.f('ck_payments_provider_status_enum_values'),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'SETTLED', 'FAILED', 'CANCELLED')",
            name=op.f('ck_payments_status_enum_values'),
        ),
        sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
        sa.CheckConstraint('version >= 1', name=op.f('ck_payments_version_positive')),
        sa.ForeignKeyConstraint(
            ['from_account_id'],
            ['accounts.id'],
            name=op.f('fk_payments_from_account_id_accounts'),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
        sa.UniqueConstraint('provider_payment_id', name=op.f('uq_payments_provider_payment_id')),
    )
    op.create_index('ix_payments_from_account_id', 'payments', ['from_account_id'], unique=False)
    op.create_index('ix_payments_status_updated_at', 'payments', ['status', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Удалить шесть таблиц платёжного шлюза."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status_updated_at', table_name='payments')
    op.drop_index('ix_payments_from_account_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_provider_webhook_events_received_at'), table_name='provider_webhook_events')
    op.drop_table('provider_webhook_events')
    op.drop_index(op.f('ix_processed_events_processed_at'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_unpublished', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('accounts')
    # ### end Alembic commands ###
